import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

const sections = [
  { id: "data-we-collect", title: "1. Data We Collect" },
  { id: "how-we-use-data", title: "2. How We Use Data" },
  { id: "data-retention", title: "3. Data Retention" },
  { id: "third-party-sharing", title: "4. Third-Party Sharing" },
  { id: "data-security", title: "5. Data Security" },
  { id: "user-rights", title: "6. Your Rights" },
  { id: "cookies", title: "7. Cookies & Local Storage" },
  { id: "gdpr", title: "8. GDPR (EU Users)" },
  { id: "changes", title: "9. Changes to This Policy" },
  { id: "contact", title: "10. Contact" },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Top nav */}
      <header className="sticky top-0 z-50 border-b border-border bg-white/90 backdrop-blur-md">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-primary flex items-center justify-center">
              <span className="text-white font-bold text-xs font-mono">PD</span>
            </div>
            <span className="font-semibold text-foreground">PromptDiff</span>
          </Link>
          <Link
            href="/terms"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            Terms of Service
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 w-full py-12">
        <div className="mb-10">
          <p className="text-xs font-semibold uppercase tracking-wider text-primary mb-2">
            Legal
          </p>
          <h1 className="text-3xl font-bold tracking-tight text-foreground mb-3">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground">
            Last updated: March 20, 2026
          </p>
        </div>

        {/* Table of Contents */}
        <nav className="mb-10 p-4 bg-accent rounded-xl border border-border">
          <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
            Contents
          </p>
          <ul className="space-y-1.5">
            {sections.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm text-muted-foreground hover:text-primary transition-colors"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        <div className="prose prose-sm max-w-none">
          <p className="text-sm text-muted-foreground leading-relaxed mb-8">
            This Privacy Policy explains how Bizmarq (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;)
            collects, uses, and protects your personal data when you use PromptDiff
            at{" "}
            <a
              href="https://promptdiff.bizmarq.com"
              className="text-primary underline underline-offset-2"
            >
              promptdiff.bizmarq.com
            </a>
            . By using the service, you agree to the practices described in this
            policy.
          </p>

          {/* 1. Data We Collect */}
          <h2
            id="data-we-collect"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            1. Data We Collect
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            We collect the following categories of data:
          </p>

          <h3 className="text-base font-medium text-foreground mt-5 mb-2">
            Account information
          </h3>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5 mb-4">
            <li>Email address (used for authentication and communication)</li>
            <li>Password (stored as a bcrypt hash; we never store plaintext passwords)</li>
            <li>API keys (generated by us for your account access)</li>
          </ul>

          <h3 className="text-base font-medium text-foreground mt-5 mb-2">
            Usage data
          </h3>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5 mb-4">
            <li>Prompts you submit for evaluation</li>
            <li>Model outputs returned by LLM providers</li>
            <li>
              Evaluation metadata: models selected, latency, token counts, cost
            </li>
            <li>Usage statistics: number of evaluations, API call history</li>
          </ul>

          <h3 className="text-base font-medium text-foreground mt-5 mb-2">
            Payment information
          </h3>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              Payment details are collected and processed by Stripe. We do not
              store your credit card number. We receive from Stripe: billing
              email, last four digits of your card, and transaction history.
            </li>
          </ul>

          {/* 2. How We Use Data */}
          <h2
            id="how-we-use-data"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            2. How We Use Data
          </h2>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">Provide the service:</strong>{" "}
              Route prompts to LLM providers, return results, display evaluation
              history in your dashboard.
            </li>
            <li>
              <strong className="text-foreground">Billing:</strong> Track usage
              to calculate charges and process payments through Stripe.
            </li>
            <li>
              <strong className="text-foreground">Support:</strong> Respond to
              your questions and troubleshoot issues.
            </li>
            <li>
              <strong className="text-foreground">Service improvement:</strong>{" "}
              Analyze aggregated, anonymized usage patterns (not your prompts or
              outputs) to improve reliability and performance.
            </li>
            <li>
              <strong className="text-foreground">Security:</strong> Detect and
              prevent abuse, fraud, and unauthorized access.
            </li>
          </ul>

          {/* 3. Data Retention */}
          <h2
            id="data-retention"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            3. Data Retention
          </h2>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">Evaluation results</strong>{" "}
              (prompts, outputs, metadata) are stored for 90 days and then
              automatically deleted.
            </li>
            <li>
              <strong className="text-foreground">Account data</strong> (email,
              hashed password, API keys) is retained until you delete your
              account.
            </li>
            <li>
              <strong className="text-foreground">Billing records</strong> may be
              retained longer as required by applicable tax and accounting laws.
            </li>
            <li>
              When you delete your account, we delete your personal data within
              30 days, except where retention is required by law.
            </li>
          </ul>

          {/* 4. Third-Party Sharing */}
          <h2
            id="third-party-sharing"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            4. Third-Party Sharing
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            We share data with third parties only as necessary to provide the
            service:
          </p>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">LLM providers</strong>{" "}
              (Anthropic, OpenAI, Google, xAI): Your prompts are sent to the
              providers of the models you select. Each provider has their own
              privacy policy and data handling practices. We send only the prompt
              content and model parameters; we do not send your account
              information.
            </li>
            <li>
              <strong className="text-foreground">Stripe:</strong> Payment
              information is processed by Stripe in accordance with their{" "}
              <a
                href="https://stripe.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline underline-offset-2"
              >
                Privacy Policy
              </a>
              .
            </li>
            <li>
              <strong className="text-foreground">Law enforcement:</strong> We
              may disclose data if required by law, court order, or government
              request.
            </li>
          </ul>
          <p className="text-sm text-muted-foreground leading-relaxed mt-3">
            We do not sell your personal data to anyone.
          </p>

          {/* 5. Data Security */}
          <h2
            id="data-security"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            5. Data Security
          </h2>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              All data in transit is encrypted via HTTPS/TLS.
            </li>
            <li>
              Passwords are hashed using bcrypt before storage.
            </li>
            <li>
              API keys are stored securely and can be regenerated at any time from
              your dashboard.
            </li>
            <li>
              Our servers are hosted on Vultr in Tokyo, Japan.
            </li>
            <li>
              While we implement reasonable security measures, no system is 100%
              secure. We encourage you to use strong, unique passwords and keep
              your API keys confidential.
            </li>
          </ul>

          {/* 6. Your Rights */}
          <h2
            id="user-rights"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            6. Your Rights
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            You have the right to:
          </p>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">Access</strong> your data: View
              your prompts, outputs, and account information in the dashboard.
            </li>
            <li>
              <strong className="text-foreground">Export</strong> your data:
              Download your evaluation history via the API.
            </li>
            <li>
              <strong className="text-foreground">Delete</strong> your data:
              Delete individual evaluations or your entire account from the
              dashboard settings.
            </li>
            <li>
              <strong className="text-foreground">Correct</strong> your data:
              Update your email or password at any time.
            </li>
          </ul>
          <p className="text-sm text-muted-foreground leading-relaxed mt-3">
            To exercise any of these rights, use the dashboard or contact us at{" "}
            <a
              href="mailto:mai.takano@east-cloud.jp"
              className="text-primary underline underline-offset-2"
            >
              mai.takano@east-cloud.jp
            </a>
            .
          </p>

          {/* 7. Cookies & Local Storage */}
          <h2
            id="cookies"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            7. Cookies & Local Storage
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            PromptDiff uses minimal browser storage:
          </p>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">Authentication token:</strong>{" "}
              Stored in localStorage to keep you signed in. No tracking cookies are
              used.
            </li>
            <li>
              <strong className="text-foreground">No third-party cookies:</strong>{" "}
              We do not use analytics cookies, advertising cookies, or any
              third-party tracking scripts.
            </li>
          </ul>

          {/* 8. GDPR */}
          <h2
            id="gdpr"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            8. GDPR (EU Users)
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            If you are located in the European Economic Area (EEA), you have
            additional rights under the General Data Protection Regulation (GDPR):
          </p>
          <ul className="text-sm text-muted-foreground leading-relaxed space-y-2 list-disc pl-5">
            <li>
              <strong className="text-foreground">Legal basis:</strong> We process
              your data based on (a) your consent when you create an account, (b)
              the necessity to perform our contract with you, and (c) our
              legitimate interests in operating and improving the service.
            </li>
            <li>
              <strong className="text-foreground">Data portability:</strong> You
              can export your data in a structured, machine-readable format via the
              API.
            </li>
            <li>
              <strong className="text-foreground">Right to erasure:</strong> You
              can request deletion of all your personal data by deleting your
              account or contacting us.
            </li>
            <li>
              <strong className="text-foreground">Right to object:</strong> You can
              object to processing of your data for certain purposes by contacting
              us.
            </li>
            <li>
              <strong className="text-foreground">Data transfers:</strong> Your
              prompts may be sent to LLM providers whose servers are located
              outside the EEA (primarily in the United States). By using the
              service, you consent to these transfers as necessary to provide the
              service.
            </li>
          </ul>

          {/* 9. Changes */}
          <h2
            id="changes"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            9. Changes to This Policy
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We may update this Privacy Policy from time to time. When we make
            significant changes, we will notify you by email or by posting a notice
            in the dashboard. The &quot;Last updated&quot; date at the top of this page
            reflects the most recent revision. Continued use of the service after
            changes take effect constitutes acceptance of the updated policy.
          </p>

          {/* 10. Contact */}
          <h2
            id="contact"
            className="text-xl font-semibold text-foreground mt-10 mb-3 scroll-mt-20"
          >
            10. Contact
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-3">
            If you have questions about this Privacy Policy or want to exercise your
            data rights, contact us:
          </p>
          <div className="p-4 bg-accent rounded-xl border border-border">
            <p className="text-sm text-foreground font-medium">Bizmarq</p>
            <p className="text-sm text-muted-foreground mt-1">
              Email:{" "}
              <a
                href="mailto:mai.takano@east-cloud.jp"
                className="text-primary underline underline-offset-2"
              >
                mai.takano@east-cloud.jp
              </a>
            </p>
            <p className="text-sm text-muted-foreground mt-1">
              Service:{" "}
              <a
                href="https://promptdiff.bizmarq.com"
                className="text-primary underline underline-offset-2"
              >
                promptdiff.bizmarq.com
              </a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
