"""Typed dataclasses representing PromptDiff API response shapes."""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class TokenUsage:
    """Token consumption breakdown for a single model run.

    Attributes:
        input: Number of prompt tokens consumed.
        output: Number of completion tokens generated.
        total: Sum of input and output tokens.
    """

    input: int
    output: int
    total: int


@dataclass
class EvalResult:
    """Output and metrics for one model within a comparison run.

    Attributes:
        model: Model identifier (e.g. ``"claude-haiku-4-5"``).
        provider: Provider name (e.g. ``"anthropic"``).
        output: Raw text generated by the model.
        latency_ms: Wall-clock time from request dispatch to first full response, in ms.
        tokens: Token usage breakdown.
        cost_usd: Estimated cost in US dollars for this single model call.
        error: Human-readable error message if the model call failed, else ``None``.
    """

    model: str
    provider: str
    output: str
    latency_ms: int
    tokens: TokenUsage
    cost_usd: float
    error: Optional[str] = None


@dataclass
class EvalMeta:
    """Aggregate metadata computed across all model results in a comparison.

    Attributes:
        total_cost_usd: Sum of ``cost_usd`` across all successful model calls.
        fastest_model: Model ID with the lowest ``latency_ms``.
        cheapest_model: Model ID with the lowest ``cost_usd``.
    """

    total_cost_usd: float
    fastest_model: str
    cheapest_model: str


@dataclass
class CompareResponse:
    """Top-level response returned by :meth:`PromptDiff.compare`.

    Attributes:
        eval_id: Stable identifier for this evaluation run (e.g. ``"eval_abc123"``).
        results: Per-model results in the order requested.
        meta: Aggregate statistics derived from ``results``.
    """

    eval_id: str
    results: List[EvalResult]
    meta: EvalMeta


@dataclass
class ModelInfo:
    """Metadata for a single LLM available through PromptDiff.

    Attributes:
        id: Canonical model identifier used in API calls.
        name: Human-friendly display name.
        provider: Provider name (e.g. ``"openai"``, ``"anthropic"``).
        input_per_1m: Cost in USD per 1 million input tokens.
        output_per_1m: Cost in USD per 1 million output tokens.
    """

    id: str
    name: str
    provider: str
    input_per_1m: float
    output_per_1m: float


# ---------------------------------------------------------------------------
# Internal deserialization helpers
# ---------------------------------------------------------------------------

def _token_usage_from_dict(data: Dict[str, Any]) -> TokenUsage:
    return TokenUsage(
        input=int(data["input"]),
        output=int(data["output"]),
        total=int(data["total"]),
    )


def _eval_result_from_dict(data: Dict[str, Any]) -> EvalResult:
    return EvalResult(
        model=data["model"],
        provider=data["provider"],
        output=data.get("output", ""),
        latency_ms=int(data["latency_ms"]),
        tokens=_token_usage_from_dict(data["tokens"]),
        cost_usd=float(data["cost_usd"]),
        error=data.get("error"),
    )


def _eval_meta_from_dict(data: Dict[str, Any]) -> EvalMeta:
    return EvalMeta(
        total_cost_usd=float(data["total_cost_usd"]),
        fastest_model=data["fastest_model"],
        cheapest_model=data["cheapest_model"],
    )


def compare_response_from_dict(data: Dict[str, Any]) -> CompareResponse:
    """Deserialize a raw API response dict into a :class:`CompareResponse`."""
    return CompareResponse(
        eval_id=data["eval_id"],
        results=[_eval_result_from_dict(r) for r in data.get("results", [])],
        meta=_eval_meta_from_dict(data["meta"]),
    )


def model_info_from_dict(data: Dict[str, Any]) -> ModelInfo:
    """Deserialize a raw model dict into a :class:`ModelInfo`."""
    return ModelInfo(
        id=data["id"],
        name=data["name"],
        provider=data["provider"],
        input_per_1m=float(data["input_per_1m"]),
        output_per_1m=float(data["output_per_1m"]),
    )
